name: Build Eden Nightly
concurrency:
  group: build-eden-nightly-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  info: 
    runs-on: ubuntu-latest
    name: "Get info"
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
  
      - name: Get the latest release tag
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"      
        run: |
            api_url="https://api.github.com/repos/${{ github.repository }}"
            latest_release_info=$(curl -H "Authorization: token $GH_TOKEN" "$api_url/releases/latest")
            last_release_tag=$(echo "$latest_release_info" | jq -r '.tag_name')
            echo "${last_release_tag}"
            old_hash="${last_release_tag##*-}"
            echo "OLD_HASH=$old_hash" >> "$GITHUB_ENV"
       
      - name: Generate changelog
        run: |
          chmod +x ./changelog.sh
          ./changelog.sh
          
      - name: Upload tag file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tag
          path: ~/tag
          
      - name: Upload count file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: count
          path: ~/count
          
      - name: Upload changelog file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: changelog
          path: ~/changelog
          
  appimage: 
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - target: steamdeck
            runs-on: ubuntu-latest
          - target: common
            runs-on: ubuntu-latest
          - target: legacy
            runs-on: ubuntu-latest            
          - target: aarch64
            runs-on: ubuntu-24.04-arm
    continue-on-error: true
    container: ghcr.io/pkgforge-dev/archlinux:latest
    name: "Appimage (${{ matrix.target }})"
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - name: Set up ccache for ${{ matrix.target }}
        if: ${{ matrix.target != 'aarch64' }}
        uses: actions/cache@v4.2.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.target }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.target }}-
            
      - name: Install dependencies
        run: |
          chmod +x ./get-dependencies.sh
          ./get-dependencies.sh
          
      - name: Compile Eden ${{ matrix.target }}
        run: |
          chmod +x ./eden-appimage.sh
          ./eden-appimage.sh ${{ matrix.target }}

      - name: Upload appimage with mesa
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-mesa-appimage
          path: mesa
          
      - name: Upload appbundle with mesa
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-mesa-appbundle
          path: bundle
          
      - name: Upload appimage light
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-${{ matrix.target}}-light-appimage
          path: light        
          
  android: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [Replace, Coexist]
    continue-on-error: true
    name: "Android (${{ matrix.target }})"
    env:
      TARGET: ${{ matrix.target }}    
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get install glslang-tools libvulkan-dev -y
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
        
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Compile Eden android
        run: |
          chmod +x ./eden-android.sh
          ./eden-android.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
         name: eden-android-${{ matrix.target }}
         path: eden/src/android/artifacts/
          
  windows:
    runs-on: windows-latest
    name: "Windows (${{ matrix.target }})"
    continue-on-error: true
    strategy:
      matrix:
        include:
           - target: x86_64
             arch: x86_64
             qt_arch: win64_msvc2022_64
#           - target: x86_arm64
#             arch: ARM64
#             qt_arch: win64_msvc2022_arm64_cross_compiled
    env:
      TARGET: ${{ matrix.target }}
      ARCH: ${{ matrix.arch }}        
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.target }} 
          
      - name: Install extra tools
        run: choco install cmake 7zip wget -y --no-progress
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'windows'
          target: 'desktop'
          arch: ${{ matrix.qt_arch }}
          modules: qtmultimedia
          cache: 'true'
          
      - name: Install vulkan-sdk
        shell: bash
        run: |
           mkdir -p D:/a/_temp
           VULKAN_URL="https://sdk.lunarg.com/sdk/download/1.4.313.1/windows/vulkansdk-windows-X64-1.4.313.1.exe"
           wget -q --retry-connrefused --tries=10 "$VULKAN_URL" -O D:/a/_temp/vulkan.exe
           D:/a/_temp/vulkan.exe --accept-licenses --default-answer --confirm-command install
           echo "VULKAN_SDK=C:/VulkanSDK/1.4.313.1" >> $GITHUB_ENV
           echo "PATH=C:/VulkanSDK/1.4.313.1/Bin:$PATH" >> $GITHUB_ENV          
        
      - name: Compile Eden Windows ${{ matrix.target }}
        shell: bash
        run: |
          chmod +x ./eden-windows.sh
          ./eden-windows.sh
          
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-windows-msvc-${{ matrix.target }}
          path: eden/build/artifacts/
          
  macos:
    runs-on: ${{ matrix.runs-on }}
    name: "MacOS (${{ matrix.target }})"
    strategy:
      matrix:
       include:
          - target: x86_64
            runs-on: macos-13
          - target: arm64
            runs-on: macos-15
    continue-on-error: true
    env:
      TARGET: ${{ matrix.target }}
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-ccache-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-ccache-
            
      - name: Install dependencies
        run: |
          brew install --formula --quiet autoconf automake boost ccache ffmpeg fmt glslang hidapi libtool nasm nlohmann-json qt@6 sdl2 speexdsp zlib cmake Catch2 molten-vk vulkan-loader
        
      - name: Compile Eden MacOS (${{ matrix.target }})
        run: |
          chmod +x ./eden-macos.sh
          ./eden-macos.sh
          
      - name: Upload
        uses: actions/upload-artifact@v4.6.2
        with:
          name: eden-macos-${{ matrix.target }}
          path: eden/build/artifacts/
                    
  release:
    name: "release"
    if: ${{ github.ref_name == 'main' }}
    needs: [info, appimage, windows, macos]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-steamdeck-mesa-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-steamdeck-mesa-appbundle
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-steamdeck-light-appimage 
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-common-mesa-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-common-mesa-appbundle
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-common-light-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-legacy-mesa-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-legacy-mesa-appbundle
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-legacy-light-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-aarch64-mesa-appimage
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-aarch64-mesa-appbundle
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-aarch64-light-appimage
           
#      - uses: actions/download-artifact@v4.3.0
#        with:
#           name: eden-android-Replace
        
#      - uses: actions/download-artifact@v4.3.0
#        with:
#           name: eden-android-Coexist
        
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-windows-msvc-x86_64
        
#      - uses: actions/download-artifact@v4.3.0
#        with:
#           name: eden-windows-msvc-x86_arm64
#        continue-on-error: true
        
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-macos-x86_64
        
      - uses: actions/download-artifact@v4.3.0
        with:
           name: eden-macos-arm64
        
      - uses: actions/download-artifact@v4.3.0
        with:
           name: tag
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: count
           
      - uses: actions/download-artifact@v4.3.0
        with:
           name: changelog   
           
      - name: Generate changelog
        run: |
          echo "TAG=$(cat tag)" >> "${GITHUB_ENV}"
          echo "COUNT=$(cat count)" >> "${GITHUB_ENV}"
          echo "BODY<<EOF" >> "${GITHUB_ENV}"
          cat changelog >> "${GITHUB_ENV}"
          echo "EOF" >> "${GITHUB_ENV}"    

      - name: Release Eden
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Eden Unofficial Nightly Release: ${{ env.COUNT }}"
          tag_name: "${{ env.TAG }}"
          body: "${{ env.BODY }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            *.AppImage*, *.AppBundle*, *.7z
